version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.4
    image: python-redis-1
    ports:
      - "5000:5000"
  
  redis:
    image: "redis:alpine"